import React from "react";
import Head from "next/head";

const About = () => {
  return (
    <>
      <Head>
        <title>JPGAMES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>about page about page about page about page about page</div>
        <div>about page about page about page about page about page</div>
        <div>about page about page about page about page about page</div>
        <div>about page about page about page about page about page</div>
        <div>about page about page about page about page about page</div>
        <div>about page about page about page about page about page</div>
        <div>about page about page about page about page about page</div>
        <div>about page about page about page about page about page</div>
        <div>about page about page about page about page about page</div>
        <div>about page about page about page about page about page</div>
        <div>about page about page about page about page about page</div>
        <div>about page about page about page about page about page</div>
      </div>
    </>
  );
};

export default About;
