import React from "react";
import Head from "next/head";

const Games = () => {
  return (
    <>
      <Head>
        <title>JPGAMES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>games page games page games page games page games page</div>
      <div>games page games page games page games page games page</div>
      <div>games page games page games page games page games page</div>
      <div>games page games page games page games page games page</div>
      <div>games page games page games page games page games page</div>
      <div>games page games page games page games page games page</div>
      <div>games page games page games page games page games page</div>
      <div>games page games page games page games page games page</div>
      <div>games page games page games page games page games page</div>
      <div>games page games page games page games page games page</div>
    </>
  );
};

export default Games;
